<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <StartupObject>NexMedia.WebImageOptimiser.Desktop.Program</StartupObject>
    <Version>0.1.0-dev.4</Version>
     <ApplicationIcon>Assets\Nexmedia-app-icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Assets\Nexmedia-app-icon.ico" />
    <None Remove="Assets\loading-spinner-sheet.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../NexMedia.WebImageOptimiser.Core/NexMedia.WebImageOptimiser.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\Nexmedia-app-icon.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\loading-spinner-sheet.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
  <ItemGroup>
    <None Update="headline-rotation.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Velopack" Version="1.2.158" />
  </ItemGroup>
</Project>
